# Generated by Django 5.2.3 on 2026-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
