# Generated by Django 5.2.3 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(
                blank=True,
                help_text='Safaricom CheckoutRequestID for the STK push that was sent for this transaction.',
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cancelled_by_user', 'Cancelled by user'),
                    ('insufficient_funds', 'Insufficient funds'),
                    ('timeout', 'Timeout - phone unreachable'),
                    ('wrong_pin', 'Wrong PIN entered'),
                    ('amount_mismatch', 'Paid amount did not match transaction'),
                    ('provisioning_failed', 'Payment received but router provisioning failed'),
                    ('other', 'Other/unrecognized failure'),
                ],
                help_text='Normalized reason a payment failed or a callback was rejected.',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_tr_checkou_9b3f1a_idx'),
        ),
    ]
