# Generated by Django 5.2.3 on 2026-07-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_checkou_34e8a5_idx',
            old_name='payments_tr_checkou_9b3f1a_idx',
        ),
    ]
