# Generated by Django 5.2.3 on 2026-07-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0002_bandwidthallocation_transaction_hotspotuser_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WanSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(help_text="WAN interface name (e.g. 'ether1')", max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rx_bytes', models.BigIntegerField(blank=True, help_text='Cumulative rx-byte counter at sample time (null if the router was unreachable)', null=True)),
                ('tx_bytes', models.BigIntegerField(blank=True, help_text='Cumulative tx-byte counter at sample time (null if the router was unreachable)', null=True)),
                ('interval_seconds', models.FloatField(blank=True, help_text='Seconds since the previous sample for this router+interface', null=True)),
                ('down_mbps', models.FloatField(blank=True, help_text='Average download throughput over the interval, derived from the rx_bytes delta', null=True)),
                ('up_mbps', models.FloatField(blank=True, help_text='Average upload throughput over the interval, derived from the tx_bytes delta', null=True)),
                ('latency_ms', models.FloatField(blank=True, help_text='Average ping RTT in milliseconds', null=True)),
                ('packet_loss_pct', models.FloatField(blank=True, help_text='Ping packet loss percentage', null=True)),
                ('reachable', models.BooleanField(default=True, help_text='Whether the router responded to this sampling attempt')),
                ('router', models.ForeignKey(help_text='Router this WAN sample was taken from', on_delete=django.db.models.deletion.PROTECT, related_name='wan_samples', to='network_management.router')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['router', 'interface', 'timestamp'], name='network_man_router__538e34_idx')],
            },
        ),
    ]
