# Generated by Django 5.2.3 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0003_wansample'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='manages_hotspot_users',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether SurfZone is allowed to create, modify, or remove hotspot/PPPoE "
                    "users on this router. Off by default - must be explicitly enabled per "
                    "router before any code path is allowed to write user entries to it."
                ),
            ),
        ),
    ]
