# Generated by Django 5.2.3 on 2026-07-24 00:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0004_router_manages_hotspot_users'),
        ('service_operations', '0001_initial'),
        ('payments', '0002_transaction_checkout_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, help_text="Site label, snapshotted from Router.location at creation time. There is no separate Site model in this codebase yet - this is a denormalized copy so historical sessions don't drift if the router's location field changes later.", max_length=100)),
                ('mac_address', models.CharField(db_index=True, help_text="MikroTik 'mac' param", max_length=17)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text="MikroTik 'ip' param", null=True)),
                ('link_login_url', models.URLField(blank=True, help_text="MikroTik 'link-login-only' param - where the portal POSTs credentials back to the router.", max_length=1000)),
                ('link_orig_url', models.URLField(blank=True, help_text="MikroTik 'link-orig' param - the destination the client originally requested.", max_length=1000)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('landed', 'Landed on portal'), ('phone_captured', 'Phone number captured'), ('plan_selected', 'Plan selected'), ('payment_pending', 'Payment initiated, awaiting callback'), ('payment_failed', 'Payment failed'), ('activated', 'Subscription activated'), ('provisioning_failed', 'Payment received but router provisioning failed'), ('connected', 'Logged into the router'), ('abandoned', 'Abandoned/expired')], db_index=True, default='landed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Bumped whenever the portal re-fetches this session, so a closed/reopened tab resumes the same row.')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='network_management.router')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='service_operations.subscription')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['router', 'mac_address'], name='network_man_router__a1f2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['status', 'created_at'], name='network_man_status_b4d5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['mac_address', 'status'], name='network_man_mac_add_c7f8a9_idx'),
        ),
    ]
