# Generated by Django 5.2.3 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0005_portalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotuser',
            name='hotspot_secret',
            field=models.CharField(
                blank=True,
                help_text='Random per-session hotspot login secret. Never derived from any client/database ID.',
                max_length=64,
                null=True,
            ),
        ),
    ]
