# Generated by Django 5.2.3 on 2026-07-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0006_hotspotuser_hotspot_secret'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalsession',
            new_name='network_man_router__48b3b8_idx',
            old_name='network_man_router__a1f2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='portalsession',
            new_name='network_man_status_d678ac_idx',
            old_name='network_man_status_b4d5e6_idx',
        ),
        migrations.RenameIndex(
            model_name='portalsession',
            new_name='network_man_mac_add_e909d7_idx',
            old_name='network_man_mac_add_c7f8a9_idx',
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='router',
            field=models.ForeignKey(blank=True, help_text='Router that redirected this client to the portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='network_management.router'),
        ),
    ]
