# Generated by Django 5.2.3 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hotspot_username',
            field=models.CharField(
                blank=True,
                help_text="Hotspot login username for this subscription (client's own username, unless it collides with another client on the same router).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='hotspot_password',
            field=models.CharField(
                blank=True,
                help_text='Random per-subscription hotspot login secret, generated at activation time. Never derived from any client/database ID.',
                max_length=64,
                null=True,
            ),
        ),
    ]
